name: Daily schedule reminder

on:
  schedule:
        - cron: '05 7 * * *'
        - cron: '07 7 * * *'
  workflow_dispatch:

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - run: python main.py
        env:
          CALENDAR_URL: ${{ secrets.CALENDAR_URL }}
          YWEATHER_KEY: ${{ secrets.YWEATHER_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
